import type { BrandConfig, SiteKey } from "./types";

const SYS = 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif';
const INTER = `"Inter", ${SYS}`;
const ARCHIVO = `"Archivo", ${SYS}`;
const BARLOW_C = `"Barlow Condensed", ${SYS}`;
const BARLOW = `"Barlow", ${SYS}`;
const FRAUNCES = `"Fraunces", Georgia, serif`;
const GROTESK = `"Space Grotesk", ${SYS}`;
const PLAYFAIR = `"Playfair Display", Georgia, serif`;
const LORA = `"Lora", Georgia, serif`;

export const BRANDS: Record<SiteKey, BrandConfig> = {
  aflreviews: {
    key: "aflreviews",
    homeVariant: "news",
    dataNav: [
      { href: "/ladder", label: "Ladder" },
      { href: "/fixtures", label: "Fixtures" },
      { href: "/results", label: "Results" },
    ],
    name: "AFL Reviews",
    domain: "aflreviews.com.au",
    tagline: "Every match. Every angle.",
    description:
      "Independent AFL analysis: match previews, reviews, team and player breakdowns, injuries, form, statistics and finals coverage.",
    sports: ["AFL", "Australian Rules Football"],
    categories: [
      { slug: "previews", name: "Match Previews", description: "Tactical and statistical previews of upcoming AFL matches." },
      { slug: "reviews", name: "Match Reviews", description: "Post-match analysis, key moments and player performances." },
      { slug: "teams", name: "Team Analysis", description: "Club-by-club form, list management and structure analysis." },
      { slug: "players", name: "Player Analysis", description: "Individual player form, roles, matchups and statistics." },
      { slug: "injuries", name: "Injuries & Teams", description: "Injury news, team selection and late changes." },
      { slug: "stats", name: "Stats & Ladder", description: "AFL statistics, ladder analysis and finals scenarios." },
    ],
    theme: {
      bg: "#F7F8FA",
      surface: "#FFFFFF",
      text: "#101828",
      muted: "#5B6474",
      accent: "#D22730",
      accentContrast: "#FFFFFF",
      chrome: "#0B1F3A",
      chromeText: "#FFFFFF",
      border: "#E3E6EC",
      fontHeading: ARCHIVO,
      fontBody: INTER,
      headingTransform: "none",
      headingWeight: 800,
      radius: "0.5rem",
    },
    logoText: "AFL",
    logoAccentText: "Reviews",
    twitter: "@aflreviews",
  },

  ufcreview: {
    key: "ufcreview",
    homeVariant: "news",
    dataNav: [
      { href: "/events", label: "Schedule" },
    ],
    name: "UFC Review",
    domain: "ufcreview.com.au",
    tagline: "Fight cards, broken down.",
    description:
      "UFC and MMA analysis: card breakdowns, fighter statistics, style matchups, previews, results and model-vs-market observations.",
    sports: ["UFC", "MMA", "Mixed Martial Arts"],
    categories: [
      { slug: "previews", name: "Card Previews", description: "Full card breakdowns for upcoming UFC events." },
      { slug: "results", name: "Results", description: "Event results, scorecards and post-fight analysis." },
      { slug: "fighters", name: "Fighter Analysis", description: "Fighter statistics, form and career trajectories." },
      { slug: "matchups", name: "Style Matchups", description: "How styles collide: grappler vs striker, pressure vs counter." },
      { slug: "news", name: "UFC News", description: "Signings, bookings, withdrawals and card changes." },
      { slug: "model-vs-market", name: "Model vs Market", description: "Where quantitative models disagree with betting markets." },
    ],
    theme: {
      bg: "#0E0F12",
      surface: "#17181D",
      text: "#F2F3F5",
      muted: "#9BA0AC",
      accent: "#E8B71A",
      accentContrast: "#141414",
      chrome: "#08090B",
      chromeText: "#F2F3F5",
      border: "#26282F",
      fontHeading: BARLOW_C,
      fontBody: BARLOW,
      headingTransform: "uppercase",
      headingWeight: 900,
      radius: "0.25rem",
    },
    logoText: "UFC",
    logoAccentText: "Review",
    twitter: "@ufcreviewau",
  },

  puntersreview: {
    key: "puntersreview",
    homeVariant: "broadsheet",
    name: "Punters Review",
    domain: "puntersreview.com.au",
    tagline: "Racing, read properly.",
    description:
      "Australian racing analysis: race previews and reviews, track and form analysis, market moves, results and betting education.",
    sports: ["Horse Racing", "Thoroughbred Racing", "Harness Racing", "Greyhounds"],
    categories: [
      { slug: "previews", name: "Race Previews", description: "Meeting and race-by-race previews with speed maps and form." },
      { slug: "reviews", name: "Race Reviews", description: "Post-race analysis, run-on horses and black bookers." },
      { slug: "tracks", name: "Track Analysis", description: "Track conditions, bias patterns and rail movements." },
      { slug: "markets", name: "Market Analysis", description: "Market moves, firming runners and where the money is going." },
      { slug: "education", name: "Betting Education", description: "Staking, value, market percentages and punting fundamentals." },
      { slug: "news", name: "Racing News", description: "Carnival news, jockey bookings, scratchings and stewards." },
    ],
    theme: {
      bg: "#F6F3EA",
      surface: "#FFFFFF",
      text: "#1E2A24",
      muted: "#5F6B63",
      accent: "#0E5A3C",
      accentContrast: "#FFFFFF",
      chrome: "#0E3B2A",
      chromeText: "#F3EFDF",
      border: "#E2DDCB",
      chromeAccent: "#D9B64A",
      fontHeading: FRAUNCES,
      fontBody: INTER,
      headingTransform: "none",
      headingWeight: 700,
      radius: "0.375rem",
    },
    logoText: "Punters",
    logoAccentText: "Review",
    twitter: "@puntersreview",
  },

  sportinformation: {
    key: "sportinformation",
    homeVariant: "index",
    name: "Sport Information",
    domain: "sportinformation.com.au",
    tagline: "The numbers behind the game.",
    description:
      "Australian sports information: statistics, rules and explainers, historical records and data across AFL, NRL, UFC, racing, NBA and NFL.",
    sports: ["AFL", "NRL", "UFC", "Horse Racing", "NBA", "NFL"],
    categories: [
      { slug: "afl", name: "AFL", description: "AFL statistics, records, fixtures and explainers." },
      { slug: "nrl", name: "NRL", description: "NRL statistics, records and league information." },
      { slug: "ufc", name: "UFC", description: "UFC statistics, rankings and event information." },
      { slug: "racing", name: "Racing", description: "Horse racing data, carnival guides and race records." },
      { slug: "us-sports", name: "US Sports", description: "NBA and NFL statistics and information for Australian fans." },
      { slug: "explainers", name: "Rules & Explainers", description: "How sports, rules, formats and markets actually work." },
    ],
    theme: {
      bg: "#FFFFFF",
      surface: "#F6F8FB",
      text: "#0F1728",
      muted: "#526077",
      accent: "#1156D6",
      accentContrast: "#FFFFFF",
      chrome: "#FFFFFF",
      chromeText: "#0F1728",
      border: "#E4E9F1",
      fontHeading: GROTESK,
      fontBody: INTER,
      headingTransform: "none",
      headingWeight: 700,
      radius: "0.75rem",
    },
    logoText: "Sport",
    logoAccentText: "Information",
    twitter: "@sportinfoau",
  },

  punterstory: {
    key: "punterstory",
    homeVariant: "magazine",
    name: "Punter Story",
    domain: "punterstory.com.au",
    tagline: "True stories from Australian punting.",
    description:
      "The editorial home of Australian punting culture: big wins, brutal losses, unforgettable sporting moments, interviews and opinions.",
    sports: ["Horse Racing", "AFL", "UFC", "Sports Betting Culture"],
    categories: [
      { slug: "big-wins", name: "Big Wins", description: "The collects that became legend." },
      { slug: "big-losses", name: "Big Losses", description: "The days it all went wrong — told honestly." },
      { slug: "moments", name: "Sporting Moments", description: "The moments Australian sport never forgets." },
      { slug: "interviews", name: "Interviews", description: "Conversations with punters, bookies, trainers and characters." },
      { slug: "opinion", name: "Opinion", description: "Columns and perspectives on punting culture." },
      { slug: "culture", name: "Punting Culture", description: "The pubs, the TABs, the tracks and the rituals." },
    ],
    theme: {
      bg: "#FAF7F1",
      surface: "#FFFFFF",
      text: "#221E1A",
      muted: "#6B6258",
      accent: "#B4471F",
      accentContrast: "#FFFFFF",
      chrome: "#FAF7F1",
      chromeText: "#221E1A",
      border: "#E8E1D5",
      fontHeading: PLAYFAIR,
      fontBody: LORA,
      headingTransform: "none",
      headingWeight: 700,
      radius: "0",
    },
    logoText: "Punter",
    logoAccentText: "Story",
    twitter: "@punterstory",
  },
};
